V0.1.2
dmcharlie19/CookBook pull request #1
Opened 2022-04-23 07:33 UTC by dmcharlie19

реализованы BE и FE приложения

2022-04-26 20:52 UTC, egoshin-igor requested changes

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Application/AppServices/IRecipeService.cs
> +    List<RecipeDto> GetRecipes();
Т.к. это RecipeService то Recipes писать не обязательно по контексту понятно
_recipeService.GetRecipes() => _recipeService.GetAll().
CreateRecipe -> Create
GetRecipe -> GetById и т.п.

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Application/AppServices/RecipeService.cs
> +      _unitOfWork.Commit();
uow commit на самом высоком уровне. В контроллере. 
Можно в CreateRecipe вернуть recipe, а и потом id вернуть

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Controllers/RecipeController.cs
> +        return _recipeService.GetRecipes().Select( x => new RecipeCommand
По названиям. Наружу все равно возвращаются Dto, т.е. RecipeDto, который лежит в Api так же.
Тут можно так же назвать RecipeDto или чтобы конфликтов в названии не было CroppedRecipeDto - лучше не придумал. Можно просто RecipeDto тоже, но тогда полное имя придется писать с неймспейсом
Для детального рецепта по id -- RecipeDetailDto.
Так же RecipeService можно разделить на две --- чтение и изменение -- RecipeQuery и RecipeManager
Вторая вариант ----
Получать сущности рецепта прям тут в контроллере и превращать в дтошку RecipeDto или RecipeDetailsDto

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Controllers/RecipeController.cs
> +        return _recipeService.GetRecipes().Select( x => new RecipeCommand
Так же сделай папку Mappers. и там класс RecipeMapper
с методами расширения 
для второго варианта
public static RecipeDto Map(this Recipe recipe)
public static RecipeDetails Map(this Recipe recipe)
для первого варианта
public static RecipeDto Map(this RecipeDto recipe)
public static RecipeDetails Map(this RecipeDto recipe)

А тут просто будешь вызывать просто x.Map()

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Controllers/RecipeController.cs
> +      try
try catch везде можешь убрать. Потом можно просто middleware написать можно который исключения ловит и определенные ошибки кидает

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Controllers/RecipeController.cs
> +    [HttpGet( "get-all" )]
тут просто пустая строка ---- api/recipes и так понятно что все по рест апи

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Controllers/RecipeController.cs
> +    public IActionResult Create( [FromBody] RecipeCommand recipeCommand )
Раздели дтошки. Для создания рецепта и для получения рецепта и для изменения рецепта могут понадобиться разные данные
RecipeDetailsDto
RecipeDto
CreateRecipeCommand
EditRecipeCommandDto

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Controllers/RecipeController.cs
> +      if ( recipeCommand.Title == null )
валидацию в сервисе можешь делать и исключения кидать. некорректные ситуации
Потом какой нить свой Exception будешь кидать --- ValidationException например.
А в middleware ловить и возвращать BadRequest

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Controllers/RecipeController.cs
> +        int id = _recipeService.CreateRecipe( new RecipeDto
тут тоже маппер из CreateRecipeCommandDto в CreateRecipeCommand. А в _recipeService.CreateRecipe принимать CreateRecipeCommand

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Controllers/RecipeController.cs
> +    public IActionResult Create( [FromBody] RecipeCommand recipeCommand )
добавление рецепта только в версии v2.0. Не стоит спешить

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Controllers/RecipeController.cs
> +        _recipeService.Delete( recipeId );
DeleteById

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Program.cs
> +// Контороллеры
опечатка

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Program.cs
> +builder.Services.AddScoped<IRecipeRepository, RecipeRepository>();
для Di можно расширения писать
Что то типа ApplicationBindings в слое Application(AddApplication(this IServiceCollection)
InfrastructureBindings и т.п.

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Program.cs
> +app.UseCors( builder => builder.WithOrigins( "http://localhost:4200" ) );
это костыль конечно. А так тебе потом nginx нужно добавить

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Program.cs
> +app.UseCors( builder => builder.WithOrigins( "http://localhost:4200" ) );
и без корс будет работать

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Properties/launchSettings.json
> +    "IIS Express": {
это можешь убрать. Вряд ли иис юзаешь. Консольки достаточно

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Application/AppServices/RecipeService.cs
> +      _recipeRepository.Delete( recipeId );
нужно проверка что такой рецепт существует. Если существует то исключение кидать

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Application/AppServices/RecipeService.cs
> +    public RecipeDto? GetRecipe( int recipeId )
тут и в GetRecipes разные дто будут. Для деталей больше данных. Для списка рецептов меньше

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Infrastructure/Foundation/CookBookDbContext.cs
> +    public DbSet<Recipe> RecipeSet { get; set; }
Просто Recipes назвать?

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Infrastructure/Repositories/RecipeRepository.cs
> +      return _dbContext.RecipeSet.ToList();
тут потом не будет списка. будет фильтрация, т.к. не все рецепты показываем. Но это потом

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookFrontend/angular.json
> +            "browserTarget": "TodoList:build"
тут и ниже неправильные названия ---TodoList

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookFrontend/src/app/common-styles.css
> +    --yellow: #FDB100;
это комментарии? Убрать нужно, если не юзаются

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookFrontend/src/app/common-styles.css
> +    --yellow: #FDB100;
Или это что то другое. Если другое то отступы поправь

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookFrontend/src/app/common-styles.css
> +.body{
форматирование. Поставь какое нить автоформатирование в ui

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookFrontend/src/app/common-styles.css
> +	/* margin: 0 8px;
комментарии лишние

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookFrontend/src/app/common-styles.css
> +.Navigation{
наименование css классов в ститле name-subname-etc. Navigation -> navigation

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookFrontend/src/app/common-styles.css
> +	.CurrentLink
единое наименование стилей юзай

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookFrontend/src/app/common-styles.css
> +.User{
отступы

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookFrontend/src/app/common-styles.css
> +	.recipes
это точно тут, а не в другом компоненте?

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookFrontend/src/app/recipes-list/recipes-list.component.html
> +                    <div style="height: 15px;"></div>
стили напрямую не пиши. В классы выводи

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookFrontend/src/app/recipes-list/recipes-list.component.html
> +            <div class="OneRecipeBox">
карточку рецепты вынеси в отдельный компонент. Он независим и переиспользуемым будет.
recipe-card

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookFrontend/src/app/recipes-list/recipes-list.component.ts
> +    LoadTodos() {
неправильное название метода

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookFrontend/src/app/recipes-list/recipes-list.component.ts
> +    LoadTodos() {
именование методов с маленькой буквы.

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookFrontend/src/app/recipes-list/recipes-list.component.ts
> +            console.log("failed load recipes");
тут в ui что то должно показаться

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookFrontend/src/app/services/recipeService.ts
> +    private url = "/api/Recipe/";
слэш убери в конце. ниже увидишь почему

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookFrontend/src/app/services/recipeService.ts
> +        return this.http.get(this.url + "get-all").pipe(catchError(err => {
интерполяция есть `${this.url}/get-all`

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Command/RecipeCommand.cs
> +namespace CookBookBackend.Api.Command
файлов миграций  не хватает для разворачивания базы?

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Command/RecipeCommand.cs
> +  public class RecipeCommand
Не соответствует дизайну надо поправить
![image](https://user-images.githubusercontent.com/24194554/165389713-41a12f65-d106-42e5-8f7d-f7fe9c40f919.png)

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Command/RecipeCommand.cs
> +  public class RecipeCommand
Ссылки никак не выделяются

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Command/RecipeCommand.cs
> +  public class RecipeCommand
Размеры кнопок не такие как на дизайне

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Command/RecipeCommand.cs
> +  public class RecipeCommand
Можешь md bootstrap подрубить или сам доверстать. в md-bootstrap такие кнопки есть.

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Command/RecipeCommand.cs
> +  public class RecipeCommand
Короче приведи к дизайну. Сделай чтобы кнопки были такие как на дизайне, отображались как кликабельные. footer чтобы не так сильно примыкал - он внизу страницы должен быть. Опечатки поправь(от шев-поваров)
Шрифты нужные скачай

2022-04-26 20:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Command/RecipeCommand.cs
> +  public class RecipeCommand
Дизайн важен. Не примут на финальной защите

2022-04-27 14:58 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Controllers/RecipeController.cs
> +  public class RecipeController : ControllerBase
RecipeController -> RecipesController

2022-04-29 05:34 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Command/RecipeCommand.cs
> +  public class RecipeCommand
ок, доработал стиль

2022-04-29 05:39 UTC, dmcharlie19 commented on CookBookFrontend/angular.json
> +            "browserTarget": "TodoList:build"
ок, заменил

2022-04-30 12:22 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Controllers/RecipeController.cs
> +    public IActionResult Create( [FromBody] RecipeCommand recipeCommand )
эти методы я пока удалю, пока чтомне не понятно какими они должны быть в итоге

2022-04-30 12:23 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Application/AppServices/IRecipeService.cs
> +    List<RecipeDto> GetRecipes();
ок

2022-04-30 12:24 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Controllers/RecipeController.cs
> +        return _recipeService.GetRecipes().Select( x => new RecipeCommand
Решил убрать Dto с уровня апи. Оставить на уровне Апп

2022-04-30 12:26 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Controllers/RecipeController.cs
> +      try
ок

2022-04-30 12:26 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Controllers/RecipeController.cs
> +    [HttpGet( "get-all" )]
ок

2022-04-30 12:27 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Controllers/RecipeController.cs
> +      if ( recipeCommand.Title == null )
ок, также на потом откладывается

2022-04-30 12:27 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Controllers/RecipeController.cs
> +        int id = _recipeService.CreateRecipe( new RecipeDto
аналогично предыдущему

2022-04-30 12:28 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Controllers/RecipeController.cs
> +    public IActionResult Create( [FromBody] RecipeCommand recipeCommand )
ок, удалил

2022-04-30 12:28 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Controllers/RecipeController.cs
> +        _recipeService.Delete( recipeId );
удалил пока что сетод

2022-04-30 12:28 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Program.cs
> +// Контороллеры
ок

2022-04-30 12:29 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Program.cs
> +builder.Services.AddScoped<IRecipeRepository, RecipeRepository>();
не совсем понял что ты предлагаешь

2022-04-30 12:30 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Program.cs
> +app.UseCors( builder => builder.WithOrigins( "http://localhost:4200" ) );
ок, пока оставлю, потом выпилю наверное

2022-04-30 12:31 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Properties/launchSettings.json
> +    "IIS Express": {
ок убрал

2022-04-30 12:32 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Application/AppServices/RecipeService.cs
> +      _recipeRepository.Delete( recipeId );
ок, остается на будущее

2022-04-30 12:32 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Application/AppServices/RecipeService.cs
> +    public RecipeDto? GetRecipe( int recipeId )
ок

2022-04-30 12:34 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Infrastructure/Foundation/CookBookDbContext.cs
> +    public DbSet<Recipe> RecipeSet { get; set; }
можно

2022-04-30 12:34 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Infrastructure/Repositories/RecipeRepository.cs
> +      return _dbContext.RecipeSet.ToList();
ок

2022-04-30 12:58 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Application/AppServices/RecipeService.cs
> +      _unitOfWork.Commit();
ок, пока не актуально

2022-05-01 09:25 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Controllers/RecipeController.cs
> +  public class RecipeController : ControllerBase
ок

2022-05-01 09:25 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Command/RecipeCommand.cs
> +namespace CookBookBackend.Api.Command
добавил миграции

2022-05-01 09:25 UTC, dmcharlie19 commented on CookBookFrontend/src/app/recipes-list/recipes-list.component.ts
> +            console.log("failed load recipes");
ок, сделал

2022-05-01 09:26 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Controllers/RecipeController.cs
> +        return _recipeService.GetRecipes().Select( x => new RecipeCommand
ок

2022-05-01 09:26 UTC, dmcharlie19 commented on CookBookFrontend/src/app/common-styles.css
> +    --yellow: #FDB100;
убрал

2022-05-01 09:27 UTC, dmcharlie19 commented on CookBookFrontend/src/app/common-styles.css
> +.body{
ок, настроил форматирование по сохранению

2022-05-01 09:28 UTC, dmcharlie19 commented on CookBookFrontend/src/app/common-styles.css
> +	/* margin: 0 8px;
ок

2022-05-01 09:29 UTC, dmcharlie19 commented on CookBookFrontend/src/app/common-styles.css
> +.Navigation{
ок, постарался везде переименовать

2022-05-01 09:29 UTC, dmcharlie19 commented on CookBookFrontend/src/app/common-styles.css
> +	.CurrentLink
ок

2022-05-01 09:30 UTC, dmcharlie19 commented on CookBookFrontend/src/app/common-styles.css
> +.User{
ок

2022-05-01 09:30 UTC, dmcharlie19 commented on CookBookFrontend/src/app/common-styles.css
> +	.recipes
вынес заголовок и футер в отдельные компоненты

2022-05-01 09:30 UTC, dmcharlie19 commented on CookBookFrontend/src/app/recipes-list/recipes-list.component.html
> +                    <div style="height: 15px;"></div>
ок

2022-05-01 09:30 UTC, dmcharlie19 commented on CookBookFrontend/src/app/recipes-list/recipes-list.component.html
> +            <div class="OneRecipeBox">
ок

2022-05-01 09:31 UTC, dmcharlie19 commented on CookBookFrontend/src/app/recipes-list/recipes-list.component.ts
> +    LoadTodos() {
ок

2022-05-01 09:31 UTC, dmcharlie19 commented on CookBookFrontend/src/app/recipes-list/recipes-list.component.ts
> +    LoadTodos() {
ок

2022-05-04 09:55 UTC, egoshin-igor requested changes

2022-05-04 09:55 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Controllers/RecipesController.cs
> +      return _recipeQuery.GetAll();
тут правильно будет еще дтошки слоя application менять в дто слоя api. Я уже писал об этом - контракты которые предоставляет слой application может отличаться от контрактов, которые выдает api. Если хочешь, то можешь оставить так, т.к. в рамках проекта вряд ли другие кейсы использования query будут,  но я не рекомендую

2022-05-04 09:55 UTC, egoshin-igor commented on CookBookBackend/CookBook.Core/Domain/Recipe.cs
> +    public int Id { get; set; }
Давай сделаем сеттеры приватными и изменять сущность в будущем будем через методы, а создавать через конструкторы. Так твоя сущность станет прозрачнее

2022-05-04 09:55 UTC, egoshin-igor commented on CookBookBackend/CookBook.Infrastructure/Repositories/UnitOfWorks.cs
> +  public class UnitOfWork : IUnitOfWork
Название файла пофикси

2022-05-04 09:55 UTC, egoshin-igor commented on CookBookFrontend/src/app/common-styles.css
> +.onHover-sizeUp {
название стилей не везде пофиксил

2022-05-04 11:50 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Controllers/RecipesController.cs
> +      return _recipeQuery.GetAll();
да, я понимаю, но специально не стал делать т.к смыла не увидел, по факут будут две одинаковые DTO.

2022-05-04 11:51 UTC, dmcharlie19 commented on CookBookFrontend/src/app/common-styles.css
> +.onHover-sizeUp {
тут надо исправить на on-hover-size-up?

2022-05-04 11:52 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Core/Domain/Recipe.cs
> +    public int Id { get; set; }
ок, сделаю

2022-05-04 11:52 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Infrastructure/Repositories/UnitOfWorks.cs
> +  public class UnitOfWork : IUnitOfWork
ок

2022-05-04 11:53 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Controllers/RecipesController.cs
> +      return _recipeQuery.GetAll();
предлагаю пока так оставить. Это же не является ошибкой. Зависимости правильно напрвлены

2022-05-05 10:36 UTC, egoshin-igor approved these changes

2022-05-05 10:36 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Migrations/20220430140646_AddNewFieldsInRecipe.cs
> +    public partial class AddNewFieldsInRecipe : Migration
обычно пишут AlterRecipe_AddNewFields

2022-05-05 10:36 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Properties/Resources.resx
> +﻿<?xml version="1.0" encoding="utf-8"?>
может выкинуть?

2022-05-05 10:36 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Properties/launchSettings.json
> +    "To_Do_List_Backend": {
TODOList

2022-05-05 10:36 UTC, egoshin-igor commented on CookBookBackend/CookBook.Application/Mappers/RecipeMapper.cs
> +  public class RecipeMapper
public static добавить

2022-05-05 10:36 UTC, egoshin-igor commented on CookBookBackend/CookBook.Application/Mappers/RecipeMapper.cs
> +    public static RecipeDto Map( Recipe r )
Map( this Recipe r )

RecipeMapper.Map( r ) -> r.Map()

2022-05-05 10:36 UTC, egoshin-igor commented on CookBookBackend/CookBook.Application/Mappers/RecipeMapper.cs
> +    public static RecipeDto Map( Recipe r )
r -> recipe

2022-05-05 10:36 UTC, egoshin-igor commented on CookBookBackend/CookBook.Application/Queries/IRecipeQuery.cs
> +    List<RecipeDto> GetAll();
IReadOnlyList лучше возвращать

2022-05-05 10:36 UTC, egoshin-igor commented on CookBookFrontend/package.json
> +  "name": "todo-list",
todo

2022-05-05 10:36 UTC, egoshin-igor commented on CookBookFrontend/src/app/app.component.ts
> +    template: `<div>
в html?

2022-05-05 10:36 UTC, egoshin-igor commented on CookBookFrontend/src/app/common-styles.css
> +.onHover-sizeUp {
hovered-link {
}

2022-05-05 10:36 UTC, egoshin-igor commented on CookBookFrontend/src/app/recipes-list/recipes-list.component.ts
> +
пустая строка лишняя

2022-05-05 10:36 UTC, egoshin-igor commented on CookBookFrontend/src/app/recipes-list/recipes-list.component.ts
> +    this.todoService.GetRecipes().subscribe(
todo

2022-05-05 10:36 UTC, egoshin-igor commented on CookBookFrontend/src/app/recipes-list/recipes-list.component.ts
> +          this.recipes.push(data[i]);
можно все за раз запушить

2022-05-05 10:36 UTC, egoshin-igor commented on CookBookFrontend/src/app/recipes-list/recipes-list.component.ts
> +        this.isServerError = true;
isLoaded

2022-05-05 11:58 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Migrations/20220430140646_AddNewFieldsInRecipe.cs
> +    public partial class AddNewFieldsInRecipe : Migration
ок

2022-05-05 12:35 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Properties/launchSettings.json
> +    "To_Do_List_Backend": {
ок

2022-05-05 12:40 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Application/Mappers/RecipeMapper.cs
> +  public class RecipeMapper
ок

2022-05-05 12:40 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Application/Mappers/RecipeMapper.cs
> +    public static RecipeDto Map( Recipe r )
ок

2022-05-05 12:40 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Application/Mappers/RecipeMapper.cs
> +    public static RecipeDto Map( Recipe r )
ок

2022-05-05 12:42 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Application/Queries/IRecipeQuery.cs
> +    List<RecipeDto> GetAll();
ок

2022-05-05 12:42 UTC, dmcharlie19 commented on CookBookFrontend/package.json
> +  "name": "todo-list",
ок

2022-05-05 12:48 UTC, dmcharlie19 commented on CookBookFrontend/src/app/app.component.ts
> +    template: `<div>
ок

2022-05-05 12:48 UTC, dmcharlie19 commented on CookBookFrontend/src/app/common-styles.css
> +.onHover-sizeUp {
ок

2022-05-05 12:49 UTC, dmcharlie19 commented on CookBookFrontend/src/app/recipes-list/recipes-list.component.ts
> +
ок

2022-05-05 12:49 UTC, dmcharlie19 commented on CookBookFrontend/src/app/recipes-list/recipes-list.component.ts
> +    this.todoService.GetRecipes().subscribe(
ок

2022-05-05 12:49 UTC, dmcharlie19 commented on CookBookFrontend/src/app/recipes-list/recipes-list.component.ts
> +          this.recipes.push(data[i]);
ок

2022-05-05 12:59 UTC, dmcharlie19 commented on CookBookFrontend/src/app/recipes-list/recipes-list.component.ts
> +        this.isServerError = true;
jr

2022-05-05 14:21 UTC, merged