V0.2
dmcharlie19/CookBook pull request #2
Opened 2022-05-11 05:56 UTC by dmcharlie19

2022-05-12 10:43 UTC, egoshin-igor requested changes

2022-05-12 10:43 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Controllers/AccountController.cs
> +      if ( authRequestDto.Login == null )
Создашь AcoountService в Api слое? С методами Registrate, Authenticate

2022-05-12 10:43 UTC, egoshin-igor commented on CookBookBackend/CookBook.Application/Entities/Users/AuthOptions.cs
> +    private const string KEY = "CookBookClientCookBookServer";
Константы в CamelCase -> Key, Issuer и т.п.

2022-05-12 10:43 UTC, egoshin-igor commented on CookBookFrontend/src/app/interceptors/error-interceptor.ts
> +        var idToken = this.accountService.getAccesToken();
var не юзаем в ts. const если не меняется переменная, let если меняется ниже

2022-05-12 10:43 UTC, egoshin-igor commented on CookBookFrontend/src/app/interceptors/error-interceptor.ts
> +        var idToken = this.accountService.getAccesToken();
типизируем все типы -> const idToken: string

2022-05-12 10:43 UTC, egoshin-igor commented on CookBookFrontend/src/app/interceptors/error-interceptor.ts
> +        var idToken = this.accountService.getAccesToken();
Именуем правильно. В данном случае это accessToken

2022-05-12 10:43 UTC, egoshin-igor commented on CookBookFrontend/src/app/recipes-list/recipes-list.component.html
> +    <!-- <div *ngIf="isLoaded">
комментарии если они не нужно удаляй

2022-05-12 10:43 UTC, egoshin-igor commented on CookBookFrontend/src/app/services/accountService.ts
> +    // getExpiration() {
лишний коммент

2022-05-27 13:28 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Controllers/AccountController.cs
> +      if ( authRequestDto.Login == null )
сделал

2022-05-27 13:31 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Application/Entities/Users/AuthOptions.cs
> +    private const string KEY = "CookBookClientCookBookServer";
ок

2022-05-27 13:32 UTC, dmcharlie19 commented on CookBookFrontend/src/app/interceptors/error-interceptor.ts
> +        var idToken = this.accountService.getAccesToken();
ок

2022-05-27 13:33 UTC, dmcharlie19 commented on CookBookFrontend/src/app/interceptors/error-interceptor.ts
> +        var idToken = this.accountService.getAccesToken();
ок

2022-05-27 13:33 UTC, dmcharlie19 commented on CookBookFrontend/src/app/interceptors/error-interceptor.ts
> +        var idToken = this.accountService.getAccesToken();
ок

2022-05-27 13:34 UTC, dmcharlie19 commented on CookBookFrontend/src/app/recipes-list/recipes-list.component.html
> +    <!-- <div *ngIf="isLoaded">
убрал

2022-05-28 18:28 UTC, egoshin-igor requested changes

2022-05-28 18:28 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Controllers/RecipesController.cs
> +    [HttpGet, Route( "" )]
Пустой роут можно не писать. Просто HttpGet

2022-05-28 18:28 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Controllers/RecipesController.cs
> +    public void AddRecipe( [FromBody] AddRecipeRequestDto addRecipeRequest )
UserId откуда берешь? Из AddRecipeRequestDto  если, то неправильно. Через апи тогда можно будет добавить рецепт за другого юзера. Бери userId из Claims

2022-05-28 18:28 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Migrations/20220513135632_AddFieldPersonCountInRecipe.cs
> +          type: "int",
tinyint можно какой нибудь юзать(byte в C#) но это так написал. Можешь не делать

2022-05-28 18:28 UTC, egoshin-igor commented on CookBookBackend/CookBook.Application/Entities/Users/AuthOptions.cs
> +  public class AuthOptions
Проверь такой кейс у JWT - авторизовался, access token устарел, клиент получает 403, ui должен будет рефрешнуть access token по рефреш токену и еще раз тот же запрос переотправляет с новым токеном. Если этого нет, то не все сделано по JWT.

2022-05-28 18:28 UTC, egoshin-igor commented on CookBookBackend/CookBook.Application/Exceptions/InvalidClientParameterException.cs
> +    protected InvalidClientParameterException( System.Runtime.Serialization.SerializationInfo info,
Зачем тебе этот конструктор? Он нужен точно?

2022-05-28 18:28 UTC, egoshin-igor commented on CookBookBackend/CookBook.Application/Repositories/IRecipeIngredientRepository.cs
> +  public interface IRecipeIngredientRepository
Этого репозитория не будет. У тебя есть рецепт, а внутри ингредиенты. Когда в репу добавляешь рецепт, то ингредиенты тоже добавляются

2022-05-28 18:28 UTC, egoshin-igor commented on CookBookBackend/CookBook.Application/Repositories/IRecipeStepRepository.cs
> +  public interface IRecipeStepRepository
Аналогично IRecipeIngredientRepository. Нужно убрать

2022-05-28 18:28 UTC, egoshin-igor commented on CookBookBackend/CookBook.Application/Repositories/ITagRecipeRepository.cs
> +  public interface ITagRecipeRepository
Аналогично IRecipeIngredientRepository. Нужно убрать

2022-05-28 18:28 UTC, egoshin-igor commented on CookBookBackend/CookBook.Application/Repositories/IUserRepository.cs
> +    void Remove( User user );
Этот метод не нужен? Есть кейс удаления юзера?

2022-05-28 18:28 UTC, egoshin-igor commented on CookBookBackend/CookBook.Application/Services/AccountService.cs
> +      _unitOfWork.Commit();
коммит на уровень выше - к контроллеру

2022-05-28 18:28 UTC, egoshin-igor commented on CookBookBackend/CookBook.Application/Services/Dto/AuthenticationResponseDto.cs
> +    public int ExpiresAt { get; set; }
DateTime тут должен быть

2022-05-28 18:28 UTC, egoshin-igor commented on CookBookBackend/CookBook.Application/Services/RecipeService.cs
> +      recipe.RecipeSteps = addRecipeRequest.CookingSteps
recipe.RecipeSteps = addRecipeRequest.CookingSteps
        .Select( recipeStep => new RecipeStep( recipeStep, recipe.Id ) )
        .ToList();

      recipe.RecipeIngredients = addRecipeRequest.RecipeIngridients
        .Select( ri => new RecipeIngredient( ri.IngridientTitle, ri.IngridientBody, recipe.Id ) )
        .ToList();
можно это в конструктор вынести или сделать у рецепта методы - AddSteps, AddIngredients, Там можно и валидацию модели сделать внутри метода в Recipe

2022-05-28 18:28 UTC, egoshin-igor commented on CookBookBackend/CookBook.Application/Services/RecipeService.cs
> +      _unitOfWork.Commit();
смотри что предлагаю - выносим uow выше в контроллер и делаем такую логику
Сервис тегов
-- сперва добавляем теги
-- возвращаем List<Tag>(созданные или уже полученные с базы)
Uow.Commit
Новые теги сохраняются у них в Tag автоматом Id появится(фреймворк проставит)
Собираем команду добавления рецепта. Поле List<Tags> будет в команде уже с тегами с Id(просто список тегов с Id у каждого тэга)
Сервис рецептов
-- Добавляем рецепт. Достаем TagId так
----список тегов в словарь - Tags.ToDictionary(x => x.Name) = tagByName
----RecipeTags получаем так command.RecipeTags.Select(x => { tag = tagByName[x.Name]; return new RecipeTag(  tag.Id ) Ну и валидация что тег есть в словаре, если нет, то исключение(такого не должно быть)
Uow.Commit в контроллере

2022-05-28 18:28 UTC, egoshin-igor commented on CookBookBackend/CookBook.Application/Services/RecipeService.cs
> +        .Select( ri => new RecipeIngredient( ri.IngridientTitle, ri.IngridientBody, recipe.Id ) )
recipe.Id   не передавать. Т.к. это дочерняя сущность, то фреймворк сам проставит его

2022-05-28 18:28 UTC, egoshin-igor commented on CookBookBackend/CookBook.Application/Services/RecipeService.cs
> +      _unitOfWork.Commit();
Есть еще такая штука --- SequenceHillo называется у mssql. При добавлении в репозитории, но до SaveChanges бд генерит Id заранее для сущности и отдает сразу приложению. Что это дает - у сущностей уже есть Id до сохранения сущности в таблицу. Это дает возможность операции сохранения и тэга и рецепта в одной Uow.Commit( в 1 транзакции). Удобно. Это если вдруг захочешь заюзать.

2022-05-28 18:28 UTC, egoshin-igor commented on CookBookBackend/CookBook.Application/Services/RecipeService.cs
> +      _unitOfWork.Commit();
ef core тоже поддерживает SequenceHilo

2022-05-28 18:28 UTC, egoshin-igor commented on CookBookBackend/CookBook.Infrastructure/Repositories/RecipeIngredientRepository.cs
> +  public class RecipeIngredientRepository : IRecipeIngredientRepository
это все уберется

2022-05-28 18:28 UTC, egoshin-igor commented on CookBookFrontend/src/app/interceptors/error-interceptor.ts
> +        console.log("intercept!");
консоль логи - это дебаг. В коде его не должно быть. Только во время дебага

2022-05-28 18:28 UTC, egoshin-igor commented on CookBookFrontend/src/app/services/accountService.ts
> +
пустая стркоа

2022-05-28 18:28 UTC, egoshin-igor commented on CookBookFrontend/src/app/services/errorService.ts
> +        var errorMessage: string = "";
var на let

2022-06-01 05:47 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Controllers/RecipesController.cs
> +    [HttpGet, Route( "" )]
ок

2022-06-01 05:47 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Controllers/RecipesController.cs
> +    public void AddRecipe( [FromBody] AddRecipeRequestDto addRecipeRequest )
я еще не сделал связь рецепта и пользователя

2022-06-01 05:47 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Migrations/20220513135632_AddFieldPersonCountInRecipe.cs
> +          type: "int",
ладно

2022-06-01 05:48 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Application/Entities/Users/AuthOptions.cs
> +  public class AuthOptions
рефреш токен не делал еще

2022-06-01 05:49 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Application/Exceptions/InvalidClientParameterException.cs
> +    protected InvalidClientParameterException( System.Runtime.Serialization.SerializationInfo info,
нет, убрал

2022-06-01 05:51 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Application/Repositories/IRecipeIngredientRepository.cs
> +  public interface IRecipeIngredientRepository
убрал

2022-06-01 05:51 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Application/Repositories/IRecipeStepRepository.cs
> +  public interface IRecipeStepRepository
убрал

2022-06-01 05:52 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Application/Repositories/IUserRepository.cs
> +    void Remove( User user );
пока нет, убрал

2022-06-01 05:55 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Application/Services/AccountService.cs
> +      _unitOfWork.Commit();
ок

2022-06-01 06:46 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Application/Services/RecipeService.cs
> +      recipe.RecipeSteps = addRecipeRequest.CookingSteps
ок сделал

2022-06-01 08:30 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Application/Services/RecipeService.cs
> +      _unitOfWork.Commit();
Вроде все сделал, но с SequenceHilo разобраться не смог, хотя выглядит интересно

2022-06-01 08:30 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Infrastructure/Repositories/RecipeIngredientRepository.cs
> +  public class RecipeIngredientRepository : IRecipeIngredientRepository
ок

2022-06-01 08:39 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Application/Services/RecipeService.cs
> +        .Select( ri => new RecipeIngredient( ri.IngridientTitle, ri.IngridientBody, recipe.Id ) )
ок

2022-06-07 09:00 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Application/Repositories/ITagRecipeRepository.cs
> +  public interface ITagRecipeRepository
ок

2022-06-07 13:50 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Controllers/RecipesController.cs
> +    public void AddRecipe( [FromBody] AddRecipeRequestDto addRecipeRequest )
сделал

2022-06-07 14:44 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Application/Services/Dto/AuthenticationResponseDto.cs
> +    public int ExpiresAt { get; set; }
исправил, также сделал разлогирование по истечению времени

2022-06-07 14:44 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Application/Entities/Users/AuthOptions.cs
> +  public class AuthOptions
сделал выход по истечению таймаута

2022-06-07 14:47 UTC, dmcharlie19 commented on CookBookFrontend/src/app/interceptors/error-interceptor.ts
> +        console.log("intercept!");
убрал

2022-06-07 14:48 UTC, dmcharlie19 commented on CookBookFrontend/src/app/services/accountService.ts
> +
убрал

2022-06-07 14:49 UTC, dmcharlie19 commented on CookBookFrontend/src/app/services/errorService.ts
> +        var errorMessage: string = "";
ок

2022-06-11 09:35 UTC, egoshin-igor approved these changes

2022-06-11 09:35 UTC, egoshin-igor commented on CookBookBackend/CookBook.Core/Domain/Recipe.cs
> +        [Required]
можешь оставить конечно. Но такую валидацию в модель не суют обычно. Слишком низкоуровневые вещи. Обычно так валидируют команду создания рецепта, или логику проверки в обновлении такую делают.

2022-06-11 09:35 UTC, egoshin-igor commented on CookBookBackend/CookBook.Core/Domain/Recipe.cs
> +                throw new InvalidClientParameterException( "��������� ������������ ���������� ������������" );
кодировку поправь

2022-06-11 09:35 UTC, egoshin-igor commented on CookBookBackend/CookBook.Core/Domain/Recipe.cs
> +            Tags = new();
у тебя метод врет. Написано AddTags, а он полностью перезаписывает вместо добавления. Название мб поменяй

2022-06-13 12:24 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Core/Domain/Recipe.cs
> +        [Required]
ладно

2022-06-13 12:28 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Core/Domain/Recipe.cs
> +                throw new InvalidClientParameterException( "��������� ������������ ���������� ������������" );
ок

2022-06-13 12:32 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Core/Domain/Recipe.cs
> +            Tags = new();
ок, поменял логику

2022-06-13 12:47 UTC, merged