Images
dmcharlie19/CookBook pull request #4
Opened 2022-06-16 08:20 UTC by dmcharlie19

2022-06-20 06:52 UTC, egoshin-igor requested changes

2022-06-20 06:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Controllers/RecipesController.cs
> +                throw new InvalidClientParameterException( "�������� ���������� ������" );
кодировка

2022-06-20 06:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Controllers/RecipesController.cs
> +                throw new InvalidClientParameterException( "������������ ������" );
кодировка

2022-06-20 06:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Controllers/RecipesController.cs
> +            _recipeService.AddRecipe( int.Parse( userIdString ), addRecipeRequest, tags, imgPath );
в 1 команду собери.

2022-06-20 06:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Controllers/RecipesController.cs
> +            _recipeService.AddRecipe( int.Parse( userIdString ), addRecipeRequest, tags, imgPath );
ну у тебя разделения дтошек все таки нет. контракт который пришел из фронта, ты отправляешь напрямую в application. Ну тут уж что поделать. Править уже поздно

2022-06-20 06:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Controllers/RecipesController.cs
> +        [HttpGet, Route( "User/{userId}" )]
users

2022-06-20 06:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Controllers/RecipesController.cs
> +        [HttpGet, Route( "Image/{recipeId}" )]
images/recipeId

2022-06-20 06:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Controllers/RecipesController.cs
> +            if ( path != "" )
path == "", а такое может быть, что картинки нет? Если не может, то нужно исключение кидать

2022-06-20 06:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/Controllers/RecipesController.cs
> +        [Route( "Search/{searchRequest}" )]
search

2022-06-20 06:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Api/CookBook.Api.csproj
> +    <Folder Include="Resources\Images\" />
это зачем тебе?

2022-06-20 06:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Application/Services/ImageService.cs
> +            _folderName = Path.Combine( "Resources", "Images" );
это неправильное решение. у тебя статика будет локально хранится в машине. Масштабируемость исчезает. Давай вынесем в конфиг. И ты путь базовый из конфига будешь брать.

2022-06-20 06:52 UTC, egoshin-igor commented on CookBookBackend/CookBook.Infrastructure/Queries/RecipeQuery.cs
> +                        var recipeDto = r.Map();
3 строчки ниже в map засунь просто

2022-06-23 10:13 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Controllers/RecipesController.cs
> +                throw new InvalidClientParameterException( "�������� ���������� ������" );
ок

2022-06-23 10:13 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Controllers/RecipesController.cs
> +                throw new InvalidClientParameterException( "������������ ������" );
ок

2022-06-23 10:49 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Controllers/RecipesController.cs
> +            _recipeService.AddRecipe( int.Parse( userIdString ), addRecipeRequest, tags, imgPath );
не понимаю что в этом плохого, кажется в этом нет прямой необходимости

2022-06-23 10:49 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Controllers/RecipesController.cs
> +        [HttpGet, Route( "Image/{recipeId}" )]
ок

2022-06-23 10:50 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Controllers/RecipesController.cs
> +            if ( path != "" )
да, это я не продумал

2022-06-23 10:52 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Controllers/RecipesController.cs
> +        [Route( "Search/{searchRequest}" )]
ок

2022-06-23 10:54 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/CookBook.Api.csproj
> +    <Folder Include="Resources\Images\" />
убрал

2022-06-23 11:20 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Application/Services/ImageService.cs
> +            _folderName = Path.Combine( "Resources", "Images" );
сделал

2022-06-23 11:25 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Infrastructure/Queries/RecipeQuery.cs
> +                        var recipeDto = r.Map();
ок

2022-06-23 11:32 UTC, merged

2022-06-23 11:36 UTC, dmcharlie19 commented on CookBookBackend/CookBook.Api/Controllers/RecipesController.cs
> +        [HttpGet, Route( "User/{userId}" )]
ок